name: Dispatch submission to private evaluator

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: read

jobs:
  dispatch:
    if: | 
      contains(github.event.issue.labels.*.name, 'submission')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Extract submission data
        id: extract
        run: python issue-extract.py
      - name: Show json file
        run: | 
          cat payload.json
      - name: Send to Eval Repo
        env:
          TOKEN: ${{ secrets.EVAL_TOKEN }}
        run: |
          jq -c --arg et test_result '{event_type:$et, client_payload:.}' payload.json > body.json
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/WeDoWind/Static-Yaw-Ground-Truth-Challenge-Evaluation/dispatches \
            -d @body.json
